import type { CategoryProps, ProductProps } from '@/types/product/dto';

export const dummyCategoriesApi: CategoryProps[] = [
  // ===== 실물 상품 =====
  {
    category_id: 1,
    code: 'mobile',
    name: '모바일 기기',
    is_plan: false,
    is_monthly: true,
  },
  {
    category_id: 2,
    code: 'wearable',
    name: '웨어러블',
    is_plan: false,
    is_monthly: true,
  },
  {
    category_id: 3,
    code: 'accessory',
    name: '악세서리',
    is_plan: false,
    is_monthly: false,
  },

  // ===== 요금제 =====
  {
    category_id: 10,
    code: 'mobile_plan_5g',
    name: '5G 요금제',
    is_plan: true,
    is_monthly: true,
  },
  {
    category_id: 11,
    code: 'mobile_plan_lte',
    name: 'LTE 요금제',
    is_plan: true,
    is_monthly: true,
  },
  {
    category_id: 12,
    code: 'kids_plan',
    name: '키즈 요금제',
    is_plan: true,
    is_monthly: true,
  },
  {
    category_id: 13,
    code: 'watch_plan',
    name: '워치 요금제',
    is_plan: true,
    is_monthly: true,
  },
  {
    category_id: 14,
    code: 'internet_plan',
    name: '인터넷 요금제',
    is_plan: true,
    is_monthly: true,
  },
  {
    category_id: 15,
    code: 'iptv_plan',
    name: 'IPTV 요금제',
    is_plan: true,
    is_monthly: true,
  },
];

export const dummyProductsApi: ProductProps[] = [
  // ================= 모바일 기기 =================
  {
    product_id: 1,
    name: '갤럭시 S24 울트라',
    desc: '최신 AI 기능의 프리미엄 스마트폰',
    category: 'mobile',
    content: '6.8인치 디스플레이, 200MP 카메라',
    link: 'https://www.lguplus.com/mobile/s24-ultra',
    img: 'https://www.lguplus.com/images/mobile/s24-ultra.png',
    is_sale: true,
    price: 1450000,
  },
  {
    product_id: 2,
    name: '갤럭시 Z 폴드5',
    desc: '대화면 폴더블 스마트폰',
    category: 'mobile',
    content: '7.6인치 메인 디스플레이',
    link: 'https://www.lguplus.com/mobile/z-fold5',
    img: 'https://www.lguplus.com/images/mobile/z-fold5.png',
    is_sale: true,
    price: 1890000,
  },
  {
    product_id: 3,
    name: '갤럭시 Z 플립5',
    desc: '컴팩트한 폴더블폰',
    category: 'mobile',
    content: '플렉스 윈도우 지원',
    link: 'https://www.lguplus.com/mobile/z-flip5',
    img: 'https://www.lguplus.com/images/mobile/z-flip5.png',
    is_sale: true,
    price: 1250000,
  },
  {
    product_id: 4,
    name: '아이폰 15 프로',
    desc: 'A17 Pro 칩셋 탑재',
    category: 'mobile',
    content: '티타늄 디자인, 프로 카메라',
    link: 'https://www.lguplus.com/mobile/iphone-15-pro',
    img: 'https://www.lguplus.com/images/mobile/iphone-15-pro.png',
    is_sale: true,
    price: 1550000,
  },
  {
    product_id: 5,
    name: '아이폰 14',
    desc: null,
    category: 'mobile',
    content: '안정적인 성능의 베스트셀러',
    link: 'https://www.lguplus.com/mobile/iphone-14',
    img: 'https://www.lguplus.com/images/mobile/iphone-14.png',
    is_sale: true,
    price: 1090000,
  },

  // ================= 웨어러블 =================
  {
    product_id: 6,
    name: '애플 워치 시리즈 9',
    desc: '밝아진 디스플레이와 빠른 성능',
    category: 'wearable',
    content: '건강 측정, 운동 트래킹',
    link: 'https://www.lguplus.com/wearable/apple-watch-9',
    img: 'https://www.lguplus.com/images/wearable/apple-watch-9.png',
    is_sale: true,
    price: 599000,
  },
  {
    product_id: 7,
    name: '애플 워치 SE',
    desc: '가성비 스마트워치',
    category: 'wearable',
    content: '기본 건강 관리 기능 제공',
    link: 'https://www.lguplus.com/wearable/apple-watch-se',
    img: 'https://www.lguplus.com/images/wearable/apple-watch-se.png',
    is_sale: true,
    price: 359000,
  },
  {
    product_id: 8,
    name: '갤럭시 워치 6',
    desc: '수면·운동 관리 최적화',
    category: 'wearable',
    content: '체성분 측정 지원',
    link: 'https://www.lguplus.com/wearable/galaxy-watch-6',
    img: 'https://www.lguplus.com/images/wearable/galaxy-watch-6.png',
    is_sale: true,
    price: 369000,
  },
  {
    product_id: 9,
    name: '갤럭시 워치 6 클래식',
    desc: '회전 베젤 디자인',
    category: 'wearable',
    content: '프리미엄 스테인리스 바디',
    link: 'https://www.lguplus.com/wearable/galaxy-watch-6-classic',
    img: 'https://www.lguplus.com/images/wearable/galaxy-watch-6-classic.png',
    is_sale: true,
    price: 429000,
  },
  {
    product_id: 10,
    name: '갤럭시 버즈2 프로',
    desc: '프리미엄 무선 이어폰',
    category: 'wearable',
    content: '액티브 노이즈 캔슬링',
    link: 'https://www.lguplus.com/wearable/buds2-pro',
    img: 'https://www.lguplus.com/images/wearable/buds2-pro.png',
    is_sale: true,
    price: 279000,
  },

  // ================= 5G 요금제 =================
  {
    product_id: 11,
    name: '5G 프리미어 슈퍼',
    desc: '완전 무제한 요금제',
    category: 'mobile_plan_5g',
    content: '5G 데이터 무제한',
    link: 'https://www.lguplus.com/plan/5g-premier-super',
    img: 'https://www.lguplus.com/images/plan/5g-premier-super.png',
    is_sale: true,
    price: 95000,
  },
  {
    product_id: 12,
    name: '5G 프리미어',
    desc: '고용량 데이터 요금제',
    category: 'mobile_plan_5g',
    content: '테더링 80GB 제공',
    link: 'https://www.lguplus.com/plan/5g-premier',
    img: 'https://www.lguplus.com/images/plan/5g-premier.png',
    is_sale: false,
    price: 85000,
  },
  {
    product_id: 13,
    name: '5G 스탠다드',
    desc: '합리적인 5G 요금제',
    category: 'mobile_plan_5g',
    content: '데이터 150GB',
    link: 'https://www.lguplus.com/plan/5g-standard',
    img: 'https://www.lguplus.com/images/plan/5g-standard.png',
    is_sale: false,
    price: 75000,
  },
  {
    product_id: 14,
    name: '5G 슬림',
    desc: '5G 입문 요금제',
    category: 'mobile_plan_5g',
    content: '데이터 10GB',
    link: 'https://www.lguplus.com/plan/5g-slim',
    img: 'https://www.lguplus.com/images/plan/5g-slim.png',
    is_sale: true,
    price: 55000,
  },
  {
    product_id: 15,
    name: '5G 시니어',
    desc: '시니어 전용 요금제',
    category: 'mobile_plan_5g',
    content: '데이터 20GB',
    link: 'https://www.lguplus.com/plan/5g-senior',
    img: 'https://www.lguplus.com/images/plan/5g-senior.png',
    is_sale: true,
    price: 45000,
  },

  // ================= LTE 요금제 =================
  {
    product_id: 16,
    name: 'LTE 데이터 33',
    desc: '가성비 LTE 요금제',
    category: 'mobile_plan_lte',
    content: '데이터 33GB',
    link: 'https://www.lguplus.com/plan/lte-33',
    img: 'https://www.lguplus.com/images/plan/lte-33.png',
    is_sale: true,
    price: 33000,
  },
  {
    product_id: 17,
    name: 'LTE 데이터 44',
    desc: '중용량 LTE 요금제',
    category: 'mobile_plan_lte',
    content: '데이터 44GB',
    link: 'https://www.lguplus.com/plan/lte-44',
    img: 'https://www.lguplus.com/images/plan/lte-44.png',
    is_sale: false,
    price: 44000,
  },
  {
    product_id: 18,
    name: 'LTE 데이터 66',
    desc: '고용량 LTE 요금제',
    category: 'mobile_plan_lte',
    content: '데이터 66GB',
    link: 'https://www.lguplus.com/plan/lte-66',
    img: 'https://www.lguplus.com/images/plan/lte-66.png',
    is_sale: true,
    price: 66000,
  },
  {
    product_id: 19,
    name: 'LTE 시니어 24',
    desc: '시니어 전용 LTE 요금제',
    category: 'mobile_plan_lte',
    content: '데이터 24GB',
    link: 'https://www.lguplus.com/plan/lte-senior',
    img: 'https://www.lguplus.com/images/plan/lte-senior.png',
    is_sale: true,
    price: 24000,
  },
  {
    product_id: 20,
    name: 'LTE 청소년',
    desc: '청소년 전용 요금제',
    category: 'mobile_plan_lte',
    content: '데이터 10GB',
    link: 'https://www.lguplus.com/plan/lte-youth',
    img: 'https://www.lguplus.com/images/plan/lte-youth.png',
    is_sale: false,
    price: 19000,
  },
  {
    product_id: 201,
    name: '키즈 스마트 5GB',
    desc: '아이를 위한 기본 요금제',
    category: 'kids_plan',
    content: '데이터 5GB, 위치 확인, 유해 콘텐츠 차단',
    link: 'https://www.lguplus.com/plan/kids-5gb',
    img: 'https://www.lguplus.com/images/plan/kids-5gb.png',
    is_sale: true,
    price: 22000,
  },
  {
    product_id: 202,
    name: '키즈 스마트 10GB',
    desc: '데이터 넉넉한 키즈 요금제',
    category: 'kids_plan',
    content: '데이터 10GB, 보호자 관리 기능',
    link: 'https://www.lguplus.com/plan/kids-10gb',
    img: 'https://www.lguplus.com/images/plan/kids-10gb.png',
    is_sale: false,
    price: 27500,
  },
  {
    product_id: 203,
    name: '키즈 안심 무제한',
    desc: '아이 전용 무제한 요금제',
    category: 'kids_plan',
    content: '속도 제한 무제한, 통화·문자 무제한',
    link: 'https://www.lguplus.com/plan/kids-unlimited',
    img: 'https://www.lguplus.com/images/plan/kids-unlimited.png',
    is_sale: true,
    price: 33000,
  },
  {
    product_id: 204,
    name: '키즈 워치 전용',
    desc: '키즈 워치 사용 전용 요금제',
    category: 'kids_plan',
    content: '데이터 1GB, 음성 통화 중심',
    link: 'https://www.lguplus.com/plan/kids-watch',
    img: 'https://www.lguplus.com/images/plan/kids-watch.png',
    is_sale: false,
    price: 11000,
  },
  {
    product_id: 205,
    name: '키즈 입문 요금제',
    desc: null,
    category: 'kids_plan',
    content: '데이터 2GB, 기본 통화 제공',
    link: 'https://www.lguplus.com/plan/kids-basic',
    img: 'https://www.lguplus.com/images/plan/kids-basic.png',
    is_sale: true,
    price: 16500,
  },
  {
    product_id: 211,
    name: '워치 LTE 베이직',
    desc: '스마트워치 기본 요금제',
    category: 'watch_plan',
    content: 'LTE 데이터 1GB, 스마트폰 연동',
    link: 'https://www.lguplus.com/plan/watch-basic',
    img: 'https://www.lguplus.com/images/plan/watch-basic.png',
    is_sale: true,
    price: 11000,
  },
  {
    product_id: 212,
    name: '워치 LTE 스탠다드',
    desc: '일상 사용에 적합한 요금제',
    category: 'watch_plan',
    content: 'LTE 데이터 3GB',
    link: 'https://www.lguplus.com/plan/watch-standard',
    img: 'https://www.lguplus.com/images/plan/watch-standard.png',
    is_sale: false,
    price: 16500,
  },
  {
    product_id: 213,
    name: '워치 LTE 무제한',
    desc: '워치 전용 무제한 요금제',
    category: 'watch_plan',
    content: '속도 제한 무제한 데이터',
    link: 'https://www.lguplus.com/plan/watch-unlimited',
    img: 'https://www.lguplus.com/images/plan/watch-unlimited.png',
    is_sale: true,
    price: 22000,
  },
  {
    product_id: 214,
    name: '워치 키즈 연동',
    desc: '키즈 워치 연동 전용 요금제',
    category: 'watch_plan',
    content: '위치 추적, 보호자 관리 기능',
    link: 'https://www.lguplus.com/plan/watch-kids',
    img: 'https://www.lguplus.com/images/plan/watch-kids.png',
    is_sale: true,
    price: 9900,
  },
  {
    product_id: 215,
    name: '워치 시니어',
    desc: '시니어 맞춤 워치 요금제',
    category: 'watch_plan',
    content: '데이터 500MB, 음성 통화 중심',
    link: 'https://www.lguplus.com/plan/watch-senior',
    img: 'https://www.lguplus.com/images/plan/watch-senior.png',
    is_sale: false,
    price: 8800,
  },
  {
    product_id: 221,
    name: 'U+ 인터넷 100M',
    desc: '1인 가구에 적합한 요금제',
    category: 'internet_plan',
    content: '최대 100Mbps 속도',
    link: 'https://www.lguplus.com/internet/100m',
    img: 'https://www.lguplus.com/images/internet/internet-100m.png',
    is_sale: true,
    price: 22000,
  },
  {
    product_id: 222,
    name: 'U+ 인터넷 500M',
    desc: '가정용 표준 인터넷',
    category: 'internet_plan',
    content: '최대 500Mbps 속도',
    link: 'https://www.lguplus.com/internet/500m',
    img: 'https://www.lguplus.com/images/internet/internet-500m.png',
    is_sale: true,
    price: 33000,
  },
  {
    product_id: 223,
    name: 'U+ 인터넷 1G',
    desc: '초고속 인터넷 요금제',
    category: 'internet_plan',
    content: '최대 1Gbps 속도',
    link: 'https://www.lguplus.com/internet/1g',
    img: 'https://www.lguplus.com/images/internet/internet-1g.png',
    is_sale: false,
    price: 38500,
  },
  {
    product_id: 224,
    name: 'U+ 인터넷 슬림',
    desc: '가성비 중심 요금제',
    category: 'internet_plan',
    content: '100Mbps, 기본 사용 적합',
    link: 'https://www.lguplus.com/internet/slim',
    img: 'https://www.lguplus.com/images/internet/internet-slim.png',
    is_sale: true,
    price: 19800,
  },
  {
    product_id: 225,
    name: 'U+ 인터넷 패밀리',
    desc: '결합 할인 요금제',
    category: 'internet_plan',
    content: '모바일 결합 시 할인 제공',
    link: 'https://www.lguplus.com/internet/family',
    img: 'https://www.lguplus.com/images/internet/internet-family.png',
    is_sale: false,
    price: 44000,
  },
  {
    product_id: 231,
    name: 'U+ IPTV 베이직',
    desc: '필수 채널 중심 요금제',
    category: 'iptv_plan',
    content: '지상파 및 인기 채널 제공',
    link: 'https://www.lguplus.com/iptv/basic',
    img: 'https://www.lguplus.com/images/iptv/iptv-basic.png',
    is_sale: true,
    price: 16500,
  },
  {
    product_id: 232,
    name: 'U+ IPTV 스탠다드',
    desc: '가족용 추천 요금제',
    category: 'iptv_plan',
    content: '영화·드라마 채널 강화',
    link: 'https://www.lguplus.com/iptv/standard',
    img: 'https://www.lguplus.com/images/iptv/iptv-standard.png',
    is_sale: false,
    price: 18700,
  },
  {
    product_id: 233,
    name: 'U+ IPTV 프리미엄',
    desc: '최고급 콘텐츠 요금제',
    category: 'iptv_plan',
    content: '프리미엄 영화·스포츠 채널',
    link: 'https://www.lguplus.com/iptv/premium',
    img: 'https://www.lguplus.com/images/iptv/iptv-premium.png',
    is_sale: true,
    price: 20900,
  },
  {
    product_id: 234,
    name: 'U+ IPTV 키즈',
    desc: '아이 전용 콘텐츠 요금제',
    category: 'iptv_plan',
    content: '키즈·교육 콘텐츠 제공',
    link: 'https://www.lguplus.com/iptv/kids',
    img: 'https://www.lguplus.com/images/iptv/iptv-kids.png',
    is_sale: true,
    price: 11000,
  },
  {
    product_id: 235,
    name: 'U+ IPTV 스포츠',
    desc: '스포츠 팬 전용 요금제',
    category: 'iptv_plan',
    content: '국내·해외 스포츠 채널 제공',
    link: 'https://www.lguplus.com/iptv/sports',
    img: 'https://www.lguplus.com/images/iptv/iptv-sports.png',
    is_sale: false,
    price: 22000,
  },
  {
    product_id: 301,
    name: '갤럭시 S24 울트라 정품 케이스',
    desc: '슬림하고 견고한 보호 케이스',
    category: 'accessory',
    content: '충격 흡수, 무광 마감',
    link: 'https://www.lguplus.com/accessory/galaxy-s24-case',
    img: 'https://www.lguplus.com/images/accessory/galaxy-s24-case.png',
    is_sale: true,
    price: 39000,
  },
  {
    product_id: 302,
    name: '아이폰 15 프로 실리콘 케이스',
    desc: '정품 실리콘 소재',
    category: 'accessory',
    content: '부드러운 그립감, 생활 스크래치 방지',
    link: 'https://www.lguplus.com/accessory/iphone-15-case',
    img: 'https://www.lguplus.com/images/accessory/iphone-15-case.png',
    is_sale: false,
    price: 59000,
  },
  {
    product_id: 303,
    name: '고속 무선 충전 패드',
    desc: '최대 15W 고속 충전 지원',
    category: 'accessory',
    content: 'Qi 호환, 과열 방지 설계',
    link: 'https://www.lguplus.com/accessory/wireless-charger',
    img: 'https://www.lguplus.com/images/accessory/wireless-charger.png',
    is_sale: true,
    price: 49000,
  },
  {
    product_id: 304,
    name: 'USB-C 고속 충전 어댑터',
    desc: '스마트폰·태블릿 호환',
    category: 'accessory',
    content: 'PD 충전 지원, 컴팩트 디자인',
    link: 'https://www.lguplus.com/accessory/usb-c-adapter',
    img: 'https://www.lguplus.com/images/accessory/usb-c-adapter.png',
    is_sale: false,
    price: 29000,
  },
  {
    product_id: 305,
    name: '블루투스 셀카봉 삼각대',
    desc: '촬영용 악세서리',
    category: 'accessory',
    content: '리모컨 포함, 높이 조절 가능',
    link: 'https://www.lguplus.com/accessory/selfie-stick',
    img: 'https://www.lguplus.com/images/accessory/selfie-stick.png',
    is_sale: true,
    price: 19900,
  },
];
